#!/usr/bin/env bash

: "${PG_DUMP:=/usr/bin/pg_dump}"
: "${SUDO:=/usr/bin/sudo}"
: "${POSTGRES_USER:=postgres}"
: "${PG_DB_NAME:?"PG_DB_NAME not set"}"

set -eu -o pipefail

dump() {
    "$SUDO" --user="$POSTGRES_USER" "$PG_DUMP" --clean --if-exists "$PG_DB_NAME"
}

backup() {
    /usr/bin/env restic backup --tag "$PG_DB_NAME" --stdin --stdin-filename "pg-dump-${PG_DB_NAME}.sql"
}

main() {
    dump | backup
}

main
